[general]
import = ["/Users/romulo/.config/alacritty/catppuccin_mocha.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
# decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.dimensions]
columns = 200
lines = 40

[window.padding]
x = 10
y = 10

[font]
normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
bold = { family = "SauceCodePro Nerd Font", style = "Bold" }
italic = { family = "SauceCodePro Nerd Font", style = "Italic" }
bold_italic = { family = "SauceCodePro Nerd Font", style = "Bold Italic" }
size = 15.0
